### ISSUE TITLE
Flow to send data to WWOnline not working

### ISSUE THREAD

**Issue by TarunSharma22** [jtmoderate876/node-red-to-online.wonderware.com#1]
Hey, I tried to use this flow to send data to Wonderware Insight with valid bearer token but i`m getting this error in Node-Red :

![image]
(https://user-images.githubusercontent.com/31968078/60187832-e85eb200-984b-11e9-8f3c-55e21dded4cc.png)

Also now Wonderware Insight supports geolocation, so can we use that with message to send.
Any idea what may be wrong. Kindly help !!

Regards

**Comment by jtmoderate876** [comment]
Sorry, I didn't see this until just now and you have probably moved on but I will comment for those having this problem in the future:

You need to supply a Bearer token in the Credentials node in the form:
"Bearer XXX"
See the insight help under Acquire an API Key:
https://online.wonderware.com/help/#390551.htm
and enter it in the credentials node.
